/* Generated by MyraPad at 15/05/2022 05:53:41 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;


using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using System;

namespace Curse_of_the_Abyss
{
	partial class Credits: Panel
	{
		private void BuildUI()
		{
			double scale = MainMenu.scale;

			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>(MainMenu.path_to_bg);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/credits_logo.png");
			image2.Left = (int)Math.Round(640.0 * scale);
			image2.Top = (int)Math.Round(220 * scale);
			image2.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/leaderboard_bg.png");

			var textBox1 = new TextBox();
			textBox1.Text = "D";
			textBox1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox1.DisabledTextColor = Color.Black;
			textBox1.Left = (int)Math.Round(700 * scale);
			textBox1.Top = (int)Math.Round(420 * scale);
			textBox1.Enabled = false;
			textBox1.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			textBox1.DisabledBackground = new SolidBrush("#00000000");

			var textBox2 = new TextBox();
			textBox2.Text = "evelopers";
			textBox2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox2.DisabledTextColor = Color.Black;
			textBox2.Left = (int)Math.Round(725 * scale);
			textBox2.Top = (int)Math.Round(420 * scale);
			textBox2.Enabled = false;
			textBox2.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			textBox2.DisabledBackground = new SolidBrush("#00000000");

			var textBox3 = new TextBox();
			textBox3.Text = "Henry Trinh";
			textBox3.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox3.DisabledTextColor = Color.Black;
			textBox3.Left = (int)Math.Round(370 * scale);
			textBox3.Top = (int)Math.Round(480 * scale);
			textBox3.Enabled = false;
			textBox3.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox3.DisabledBackground = new SolidBrush("#00000000");

			var textBox4 = new TextBox();
			textBox4.Text = "Yan Walesch";
			textBox4.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox4.DisabledTextColor = Color.Black;
			textBox4.Left = (int)Math.Round(600 * scale);
			textBox4.Top = (int)Math.Round(480 * scale);
			textBox4.Enabled = false;
			textBox4.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox4.DisabledBackground = new SolidBrush("#00000000");

			var textBox5 = new TextBox();
			textBox5.Text = "Stefan Jokic";
			textBox5.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox5.DisabledTextColor = Color.Black;
			textBox5.Left = (int)Math.Round(840 * scale);
			textBox5.Top = (int)Math.Round(480 * scale);
			textBox5.Enabled = false;
			textBox5.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox5.DisabledBackground = new SolidBrush("#00000000");

			var textBox6 = new TextBox();
			textBox6.Text = "´";
			textBox6.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox6.DisabledTextColor = Color.Black;
			textBox6.Left = (int)Math.Round(974 * scale);
			textBox6.Top = (int)Math.Round(486 * scale);
			textBox6.Enabled = false;
			textBox6.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox6.DisabledBackground = new SolidBrush("#00000000");

			var textBox8 = new TextBox();
			textBox8.Text = "Marino Müller";
			textBox8.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox8.DisabledTextColor = Color.Black;
			textBox8.Left = (int)Math.Round(1050 * scale);
			textBox8.Top = (int)Math.Round(480 * scale);
			textBox8.Enabled = false;
			textBox8.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox8.DisabledBackground = new SolidBrush("#00000000");

			var textBox9 = new TextBox();
			textBox9.Text = "Ellen Arlt";
			textBox9.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox9.DisabledTextColor = Color.Black;
			textBox9.Left = (int)Math.Round(740 * scale);
			textBox9.Top = (int)Math.Round(520 * scale);
			textBox9.Enabled = false;
			textBox9.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox9.DisabledBackground = new SolidBrush("#00000000");

			var textBox10 = new TextBox();
			textBox10.Text = "Music and Sound Effects";
			textBox10.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox10.DisabledTextColor = Color.Black;
			textBox10.Left = (int)Math.Round(570 * scale);
			textBox10.Top = (int)Math.Round(560 * scale);
			textBox10.Enabled = false;
			textBox10.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			textBox10.DisabledBackground = new SolidBrush("#00000000");

			var textBox11 = new TextBox();
			textBox11.Text = "zapsplat com";
			textBox11.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox11.DisabledTextColor = Color.Black;
			textBox11.Left = (int)Math.Round(730 * scale);
			textBox11.Top = (int)Math.Round(620 * scale);
			textBox11.Enabled = false;
			textBox11.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox11.DisabledBackground = new SolidBrush("#00000000");

			var textBox12 = new TextBox();
			textBox12.Text = ".";
			textBox12.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox12.DisabledTextColor = Color.Black;
			textBox12.Left = (int)Math.Round(823 * scale);
			textBox12.Top = (int)Math.Round(616 * scale);
			textBox12.Enabled = false;
			textBox12.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox12.DisabledBackground = new SolidBrush("#00000000");

			var textBox13 = new TextBox();
			textBox13.Text = "mixkit com";
			textBox13.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox13.DisabledTextColor = Color.Black;
			textBox13.Left = (int)Math.Round(745 * scale);
			textBox13.Top = (int)Math.Round(640 * scale);
			textBox13.Enabled = false;
			textBox13.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox13.DisabledBackground = new SolidBrush("#00000000");

			var textBox14 = new TextBox();
			textBox14.Text = ".";
			textBox14.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox14.DisabledTextColor = Color.Black;
			textBox14.Left = (int)Math.Round(811 * scale);
			textBox14.Top = (int)Math.Round(636 * scale);
			textBox14.Enabled = false;
			textBox14.Scale = new Vector2(0.3f * (float)scale, 0.3f * (float)scale);
			textBox14.DisabledBackground = new SolidBrush("#00000000");

			var textButton1 = new TextButton();
			textButton1.Text = "Back";
			textButton1.GridColumnSpan = 0;
			textButton1.TextColor = Color.Black;
			textButton1.OverTextColor = Color.White;
			textButton1.PressedTextColor = Color.White;
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton1.PressedBackground = new SolidBrush("#00000000");
			textButton1.Left = (int)Math.Round(745 * scale);
			textButton1.Top = (int)Math.Round(730 * scale);
			textButton1.GridColumnSpan = 0;
			textButton1.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textButton1.Background = new SolidBrush("#00000000");
			textButton1.OverBackground = new SolidBrush("#00000000");
			textButton1.DisabledBackground = new SolidBrush("#00000000");
			textButton1.FocusedBackground = new SolidBrush("#00000000");
			textButton1.DisabledBorder = new SolidBrush("#00000000");

			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(textBox1);
			Widgets.Add(textBox2);
			Widgets.Add(textBox3);
			Widgets.Add(textBox4);
			Widgets.Add(textBox5);
			Widgets.Add(textBox6);
			Widgets.Add(textBox8);
			Widgets.Add(textBox9);
			Widgets.Add(textBox10);
			Widgets.Add(textBox11);
			Widgets.Add(textBox12);
			Widgets.Add(textBox13);
			Widgets.Add(textBox14);
			Widgets.Add(textButton1);


			// functionality

			textButton1.Click += (s, a) =>
			{
				Game._desktop.Root = Game._mainmenu;
			};
		}

		
	}
}
