/* Generated by MyraPad at 09/05/2022 02:47:17 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using System;

namespace Curse_of_the_Abyss
{
	partial class Exit: Panel
	{
		private void BuildUI(Game game)
		{
			double scale = MainMenu.scale;
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/MenuBackground_16_9.png");
			image1.MaxWidth = 1920;
			image1.MaxHeight = 1080;

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/exit_logo.png");
			image2.Left = (int)Math.Round(640.0 * scale);
			image2.Top = (int)Math.Round(220 * scale);
			image2.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/settings_bg.png");
			image3.Left = (int)Math.Round(525 * scale);
			image3.Top = (int)Math.Round(330 * scale);
			image3.Scale = new Vector2(0.7f * (float)scale, 0.7f * (float)scale);

			var textBox1 = new TextBox();
			textBox1.Text = "Are you sure you";
			textBox1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox1.DisabledTextColor = Color.Black;
			textBox1.Left = (int)Math.Round(630 * scale);
			textBox1.Top = (int)Math.Round(525 * scale);
			textBox1.Enabled = false;
			textBox1.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textBox1.DisabledBackground = new SolidBrush("#00000000");

			var textBox2 = new TextBox();
			textBox2.Text = "want to quit?";
			textBox2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox2.DisabledTextColor = Color.Black;
			textBox2.Left = (int)Math.Round(660 * scale);
			textBox2.Top = (int)Math.Round(565 * scale);
			textBox2.Enabled = false;
			textBox2.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textBox2.DisabledBackground = new SolidBrush("#00000000");

			var textButton1 = new TextButton();
			textButton1.Text = "Yes";
			textButton1.TextColor = Color.Black;
			textButton1.OverTextColor = Color.White;
			textButton1.PressedTextColor = Color.White;
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton1.PressedBackground = new SolidBrush("#00000000");
			textButton1.Left = (int)Math.Round(755 * scale);
			textButton1.Top = (int)Math.Round(650 * scale);
			textButton1.GridColumnSpan = 0;
			textButton1.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textButton1.Background = new SolidBrush("#00000000");
			textButton1.OverBackground = new SolidBrush("#00000000");
			textButton1.DisabledBackground = new SolidBrush("#00000000");
			textButton1.FocusedBackground = new SolidBrush("#00000000");
			textButton1.DisabledBorder = new SolidBrush("#00000000");

			var textButton2 = new TextButton();
			textButton2.Text = "No";
			textButton2.TextColor = Color.Black;
			textButton2.OverTextColor = Color.White;
			textButton2.PressedTextColor = Color.White;
			textButton2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton2.PressedBackground = new SolidBrush("#00000000");
			textButton2.Left = (int)Math.Round(765 * scale);
			textButton2.Top = (int)Math.Round(710 * scale);
			textButton2.GridColumnSpan = 0;
			textButton2.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textButton2.Background = new SolidBrush("#00000000");
			textButton2.OverBackground = new SolidBrush("#00000000");
			textButton2.DisabledBackground = new SolidBrush("#00000000");
			textButton2.FocusedBackground = new SolidBrush("#00000000");
			textButton2.DisabledBorder = new SolidBrush("#00000000");

			
			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(textBox1);
			Widgets.Add(textButton1);
			Widgets.Add(textBox2);
			Widgets.Add(textButton2);


			//functionality
			textButton1.Click += (s, a) =>
			{
				game.Exit();
			};

			textButton2.Click += (s, a) =>
			{
				Game._desktop.Root = Game._mainmenu;
			};
		}

		
	}
}
