/* Generated by MyraPad at 13/05/2022 08:08:07 */
namespace Curse_of_the_Abyss
{
	public partial class Leaderboard_entry
	{
		private int collected_eggs;
		private int total_eggs;
		private int time;
		public Leaderboard_entry(int collected_eggs, int total_eggs, int time)
		{
			this.collected_eggs = collected_eggs;
			this.total_eggs = total_eggs;
			this.time = time;
			BuildUI();
		}
	}
}