/* Generated by MyraPad at 09/05/2022 03:30:53 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using System;

namespace Curse_of_the_Abyss
{
	partial class Loading: Panel
	{
		public HorizontalProgressBar loadingbar;
		private void BuildUI()
		{
			double scale = MainMenu.scale;
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>(MainMenu.path_to_bg);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Logo.png");
			image2.Left = (int)Math.Round(530 * scale);
			image2.Top = (int)Math.Round(420 * scale);
			image2.GridRowSpan = 0;
			image2.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);

			loadingbar = new HorizontalProgressBar();
			loadingbar.Filler = new SolidBrush("#7D1D18FF");
			loadingbar.Left = (int)Math.Round(220 * scale);
			loadingbar.Top = (int)Math.Round(760 * scale);
			loadingbar.Width = (int)Math.Round(1200 * scale);
			loadingbar.Height = (int)Math.Round(40 * scale);
			loadingbar.BorderThickness = new Thickness(5);
			loadingbar.Background = new SolidBrush("#997A00FF");
			loadingbar.OverBackground = new SolidBrush("#997A00FF");
			loadingbar.DisabledBackground = new SolidBrush("#997A00FF");
			loadingbar.FocusedBackground = new SolidBrush("#997A00FF");
			loadingbar.Border = new SolidBrush("#000000FF");
			loadingbar.OverBorder = new SolidBrush("#000000FF");
			loadingbar.DisabledBorder = new SolidBrush("#000000FF");
			loadingbar.FocusedBorder = new SolidBrush("#000000FF");

			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(loadingbar);


			// functionality

			loadingbar.ValueChanged += (s, a) =>
			{
				if(loadingbar.Value >= 110f)
                {
					Game._desktop.Root = Game._mainmenu;
					Game._mainmenu.CurrState = MainMenu.State.Menu;
					Game.loading = false;
					Game.paused = false;
				}
			};
		}

		
	}
}
