/* Generated by MyraPad at 08/05/2022 16:21:58 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using System;


namespace Curse_of_the_Abyss
{
	partial class MainMenu: Panel
	{

		private void BuildUI(Game game)
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>(path_to_bg);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Logo.png");
			image2.Left = (int)Math.Round(530 * scale);
			image2.Top = (int)Math.Round(420 * scale);
			image2.GridRowSpan = 0;
			image2.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image3.Left = (int)Math.Round(670 * scale);
			image3.Top = (int)Math.Round(560 * scale);
			image3.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float)scale);

			var image4 = new Image();
			image4.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image4.Left = (int)Math.Round(670 * scale);
			image4.Top = (int)Math.Round(620 * scale);
			image4.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var image5 = new Image();
			image5.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image5.Left = (int)Math.Round(670 * scale);
			image5.Top = (int)Math.Round(680 * scale);
			image5.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var image6 = new Image();
			image6.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image6.Left = (int)Math.Round(670 * scale);
			image6.Top = (int)Math.Round(745 * scale);
			image6.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);

            var image7 = new Image();
            image7.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
            image7.Left = (int)Math.Round(670 * scale);
            image7.Top = (int)Math.Round(805 * scale);
            image7.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);

			var imageButton1 = new ImageButton();
			imageButton1.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/credits_icon.png");
			imageButton1.OverImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/credits_icon_highlight.png");
			imageButton1.PressedBackground = new SolidBrush("#00000000");
			imageButton1.Left = (int)Math.Round(1550 * scale);
			imageButton1.Top = (int)Math.Round(10 * scale);
			imageButton1.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			imageButton1.Background = new SolidBrush("#00000000");
			imageButton1.OverBackground = new SolidBrush("#00000000");
			imageButton1.DisabledBackground = new SolidBrush("#E8E8E800");
			imageButton1.FocusedBackground = new SolidBrush("#FFFFFFFF");
			imageButton1.FocusedBorder = new SolidBrush("#00000000");

			var textButton1 = new TextButton();
			textButton1.Text = "PLAY";
			textButton1.TextColor = Color.Black;
			textButton1.OverTextColor = Color.White;
			textButton1.PressedTextColor = Color.White;
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton1.PressedBackground = new SolidBrush("#00000000");
			textButton1.Left = (int)Math.Round(770 * scale);
			textButton1.Top = (int)Math.Round(565 * scale);
			textButton1.GridColumnSpan = 0;
			textButton1.Scale = new Vector2(0.25f * (float) scale, 0.25f * (float) scale);
			textButton1.Background = new SolidBrush("#00000000");
			textButton1.OverBackground = new SolidBrush("#00000000");
			textButton1.DisabledBackground = new SolidBrush("#00000000");
			textButton1.FocusedBackground = new SolidBrush("#00000000");
			textButton1.DisabledBorder = new SolidBrush("#00000000");

			var textButton4 = new TextButton();
			textButton4.Text = "tutorial";
			textButton4.TextColor = Color.Black;
			textButton4.OverTextColor = Color.White;
			textButton4.PressedTextColor = Color.White;
			textButton4.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton4.PressedBackground = new SolidBrush("#00000000");
			textButton4.Left = (int)Math.Round(732 * scale);
			textButton4.Top = (int)Math.Round(610 * scale);
			textButton4.GridColumnSpan = 0;
			textButton4.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textButton4.Background = new SolidBrush("#00000000");
			textButton4.OverBackground = new SolidBrush("#00000000");
			textButton4.DisabledBackground = new SolidBrush("#00000000");
			textButton4.FocusedBackground = new SolidBrush("#00000000");
			textButton4.DisabledBorder = new SolidBrush("#00000000");

			var textButton5 = new TextButton();
			textButton5.Text = "leaderboard";
			textButton5.TextColor = Color.Black;
			textButton5.OverTextColor = Color.White;
			textButton5.PressedTextColor = Color.White;
			textButton5.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton5.PressedBackground = new SolidBrush("#00000000");
			textButton5.Left = (int)Math.Round(702 * scale);
			textButton5.Top = (int)Math.Round(670 * scale);
			textButton5.GridColumnSpan = 0;
			textButton5.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textButton5.Background = new SolidBrush("#00000000");
			textButton5.OverBackground = new SolidBrush("#00000000");
			textButton5.DisabledBackground = new SolidBrush("#00000000");
			textButton5.FocusedBackground = new SolidBrush("#00000000");
			textButton5.DisabledBorder = new SolidBrush("#00000000");

			var textButton2 = new TextButton();
			textButton2.Text = "settings";
			textButton2.TextColor = Color.Black;
			textButton2.OverTextColor = Color.White;
			textButton2.PressedTextColor = Color.White;
			textButton2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton2.PressedBackground = new SolidBrush("#00000000");
			textButton2.Left = (int)Math.Round(735 * scale);
			textButton2.Top = (int)Math.Round(735 * scale);
			textButton2.GridColumnSpan = 0;
			textButton2.Scale = new Vector2(0.45f * (float) scale, 0.45f * (float) scale);
			textButton2.Background = new SolidBrush("#00000000");
			textButton2.OverBackground = new SolidBrush("#00000000");
			textButton2.DisabledBackground = new SolidBrush("#00000000");
			textButton2.FocusedBackground = new SolidBrush("#00000000");
			textButton2.DisabledBorder = new SolidBrush("#00000000");

			var textButton3 = new TextButton();
			textButton3.Text = "EXIT";
			textButton3.TextColor = Color.Black;
			textButton3.OverTextColor = Color.White;
			textButton3.PressedTextColor = Color.White;
			textButton3.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton3.PressedBackground = new SolidBrush("#00000000");
			textButton3.Left = (int)Math.Round(765 * scale); ;
			textButton3.Top = (int)Math.Round(810 * scale); ;
			textButton3.GridColumnSpan = 0;
			textButton3.Scale = new Vector2(0.25f * (float) scale, 0.25f * (float) scale);
			textButton3.Background = new SolidBrush("#00000000");
			textButton3.OverBackground = new SolidBrush("#00000000");
			textButton3.DisabledBackground = new SolidBrush("#00000000");
			textButton3.FocusedBackground = new SolidBrush("#00000000");
			textButton3.DisabledBorder = new SolidBrush("#00000000");

			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(image4);
			Widgets.Add(image5);
			Widgets.Add(image6);
			Widgets.Add(image7);
			Widgets.Add(textButton1);
			Widgets.Add(textButton2);
			Widgets.Add(textButton3);
			Widgets.Add(textButton4);
			Widgets.Add(textButton5);
			Widgets.Add(imageButton1);


			// functionality

			textButton1.Click += (s, a) =>
			{
				if (Game.loading)
				{
					Game._desktop.Root = loading_screen;
					Game._mainmenu.CurrState = MainMenu.State.Loading;
				}
				else
				{
					if (Game.init_pause)
                    {
						Game._timeElapsed = (int)((DateTimeOffset)DateTime.Now).ToUnixTimeMilliseconds();
						Game.init_pause = false;
					}
                    else
                    {
						Game._timePaused += (int)((DateTimeOffset)DateTime.Now).ToUnixTimeMilliseconds() - Game._pauseStart;
						Game._pauseStart = 0;
					}
					Game.paused = false;
				}
                if (Game.startup)
                {
					Game.startup = false;
					//game.current_level.play_music();
                }
			};

			textButton4.Click += (s, a) =>
			{
				Game._desktop.Root = tut0_screen;
			};

			textButton2.Click += (s, a) =>
			{
				Game._desktop.Root = settings_screen;
			};

			textButton3.Click += (s, a) =>
			{
				Game._desktop.Root = exit_screen;
			};

			textButton5.Click += (s, a) =>
			{
				Game._desktop.Root = leaderboard_screen;
			};

			imageButton1.Click += (s, a) =>
			{
				Game._desktop.Root = Game._mainmenu.credits_screen;
			};

		}

		
	}
}
