/* Generated by MyraPad at 08/05/2022 16:21:58 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using System;


namespace Curse_of_the_Abyss
{
	partial class MainMenu: Panel
	{

		private void BuildUI(Game game)
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>(path_to_bg);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Logo.png");
			image2.Left = (int)Math.Round(530 * scale);
			image2.Top = (int)Math.Round(420 * scale);
			image2.GridRowSpan = 0;
			image2.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image3.Left = (int)Math.Round(670 * scale); ;
			image3.Top = (int)Math.Round(560 * scale); ;
			image3.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float)scale);

			var image4 = new Image();
			image4.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image4.Left = (int)Math.Round(670 * scale); ;
			image4.Top = (int)Math.Round(620 * scale); ;
			image4.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var image5 = new Image();
			image5.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/Button.png");
			image5.Left = (int)Math.Round(670 * scale); ;
			image5.Top = (int)Math.Round(680 * scale); ;
			image5.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var textButton1 = new TextButton();
			textButton1.Text = "PLAY";
			textButton1.TextColor = Color.Black;
			textButton1.OverTextColor = Color.White;
			textButton1.PressedTextColor = Color.White;
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton1.PressedBackground = new SolidBrush("#00000000");
			textButton1.Left = (int)Math.Round(770 * scale); ;
			textButton1.Top = (int)Math.Round(565 * scale); ;
			textButton1.GridColumnSpan = 0;
			textButton1.Scale = new Vector2(0.25f * (float) scale, 0.25f * (float) scale);
			textButton1.Background = new SolidBrush("#00000000");
			textButton1.OverBackground = new SolidBrush("#00000000");
			textButton1.DisabledBackground = new SolidBrush("#00000000");
			textButton1.FocusedBackground = new SolidBrush("#00000000");
			textButton1.DisabledBorder = new SolidBrush("#00000000");

			var textButton2 = new TextButton();
			textButton2.Text = "settings";
			textButton2.TextColor = Color.Black;
			textButton2.OverTextColor = Color.White;
			textButton2.PressedTextColor = Color.White;
			textButton2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton2.PressedBackground = new SolidBrush("#00000000");
			textButton2.Left = (int)Math.Round(735 * scale); ;
			textButton2.Top = (int)Math.Round(610 * scale); ;
			textButton2.GridColumnSpan = 0;
			textButton2.Scale = new Vector2(0.45f * (float) scale, 0.45f * (float) scale);
			textButton2.Background = new SolidBrush("#00000000");
			textButton2.OverBackground = new SolidBrush("#00000000");
			textButton2.DisabledBackground = new SolidBrush("#00000000");
			textButton2.FocusedBackground = new SolidBrush("#00000000");
			textButton2.DisabledBorder = new SolidBrush("#00000000");

			var textButton3 = new TextButton();
			textButton3.Text = "EXIT";
			textButton3.TextColor = Color.Black;
			textButton3.OverTextColor = Color.White;
			textButton3.PressedTextColor = Color.White;
			textButton3.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton3.PressedBackground = new SolidBrush("#00000000");
			textButton3.Left = (int)Math.Round(765 * scale); ;
			textButton3.Top = (int)Math.Round(685 * scale); ;
			textButton3.GridColumnSpan = 0;
			textButton3.Scale = new Vector2(0.25f * (float) scale, 0.25f * (float) scale);
			textButton3.Background = new SolidBrush("#00000000");
			textButton3.OverBackground = new SolidBrush("#00000000");
			textButton3.DisabledBackground = new SolidBrush("#00000000");
			textButton3.FocusedBackground = new SolidBrush("#00000000");
			textButton3.DisabledBorder = new SolidBrush("#00000000");

			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(image4);
			Widgets.Add(image5);
			Widgets.Add(textButton1);
			Widgets.Add(textButton2);
			Widgets.Add(textButton3);


			// functionality

			textButton1.Click += (s, a) =>
			{
				if (Game.loading)
				{
					Game._desktop.Root = loading_screen;
					Game._mainmenu.CurrState = MainMenu.State.Loading;
				}
				else
				{
					Game.paused = false;
				}
			};

			textButton2.Click += (s, a) =>
			{
				Game._desktop.Root = settings_screen;
			};

			textButton3.Click += (s, a) =>
			{
				Game._desktop.Root = exit_screen;
			};
		}

		
	}
}
