/* Generated by MyraPad at 09/05/2022 05:14:05 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using System;

namespace Curse_of_the_Abyss
{
	partial class ScoreTime: Panel
	{
		private void BuildUI()
		{
			double scale = MainMenu.scale;

			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>(MainMenu.path_to_bg);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/score_logo.png");
			image2.Left = (int)Math.Round(640.0 * scale);
			image2.Top = (int)Math.Round(220 * scale);
			image2.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/settings_bg.png");
			image3.Left = (int)Math.Round(525 * scale);
			image3.Top = (int)Math.Round(330 * scale);
			image3.Scale = new Vector2(0.7f * (float)scale, 0.7f * (float)scale);

			var textBox1 = new TextBox();
			textBox1.Text = "Co";
			textBox1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox1.DisabledTextColor = Color.Black;
			textBox1.Left = (int)Math.Round(620 * scale);
			textBox1.Top = (int)Math.Round(460 * scale);
			textBox1.Enabled = false;
			textBox1.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			textBox1.DisabledBackground = new SolidBrush("#00000000");

			var textBox2 = new TextBox();
			textBox2.Text = " ngratulatio ";
			textBox2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox2.DisabledTextColor = Color.Black;
			textBox2.Left = (int)Math.Round(655 * scale);
			textBox2.Top = (int)Math.Round(460 * scale);
			textBox2.Enabled = false;
			textBox2.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			textBox2.DisabledBackground = new SolidBrush("#00000000");

			var textBox3 = new TextBox();
			textBox3.Text = " ns!";
			textBox3.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox3.DisabledTextColor = Color.Black;
			textBox3.Left = (int)Math.Round(868 * scale);
			textBox3.Top = (int)Math.Round(460 * scale);
			textBox3.Enabled = false;
			textBox3.Scale = new Vector2(0.5f * (float)scale, 0.5f * (float)scale);
			textBox3.DisabledBackground = new SolidBrush("#00000000");

			var textButton1 = new TextButton();
			textButton1.Text = "Next";
			textButton1.GridColumnSpan = 0;
			textButton1.TextColor = Color.Black;
			textButton1.OverTextColor = Color.White;
			textButton1.PressedTextColor = Color.White;
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton1.PressedBackground = new SolidBrush("#00000000");
			textButton1.Left = (int)Math.Round(745 * scale);
			textButton1.Top = (int)Math.Round(730 * scale);
			textButton1.GridColumnSpan = 0;
			textButton1.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textButton1.Background = new SolidBrush("#00000000");
			textButton1.OverBackground = new SolidBrush("#00000000");
			textButton1.DisabledBackground = new SolidBrush("#00000000");
			textButton1.FocusedBackground = new SolidBrush("#00000000");
			textButton1.DisabledBorder = new SolidBrush("#00000000");

			var textBox4 = new TextBox();
			textBox4.Text = "Total time";
			textBox4.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox4.DisabledTextColor = Color.Black;
			textBox4.Left = (int)Math.Round(695 * scale);
			textBox4.Top = (int)Math.Round(570 * scale);
			textBox4.Enabled = false;
			textBox4.Scale = new Vector2(0.45f * (float)scale, 0.45f * (float)scale);
			textBox4.DisabledBackground = new SolidBrush("#00000000");

			TimeSpan t = TimeSpan.FromMilliseconds(time);
			string parsed_time = string.Format("{0:D2}h:{1:D2}m:{2:D2}s:{3:D3}ms",
									t.Hours,
									t.Minutes,
									t.Seconds,
									t.Milliseconds);

			var textBox5 = new TextBox();
			textBox5.Text = parsed_time;
			textBox5.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox5.DisabledTextColor = Color.Black;
			textBox5.Left = (int)Math.Round(630 * scale);
			textBox5.Top = (int)Math.Round(620 * scale);
			textBox5.Enabled = false;
			textBox5.Scale = new Vector2(0.4f * (float)scale, 0.4f * (float)scale);
			textBox5.DisabledBackground = new SolidBrush("#00000000");


			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(textBox1);
			Widgets.Add(textBox2);
			Widgets.Add(textBox3);
			Widgets.Add(textButton1);
			Widgets.Add(textBox4);
			Widgets.Add(textBox5);


			// functionality

			textButton1.Click += (s, a) =>
			{
				Game._desktop.Root = Game._mainmenu.leaderboard_entry_screen;
			};
		}

		
	}
}
