/* Generated by MyraPad at 09/05/2022 05:14:05 */
namespace Curse_of_the_Abyss
{
	public partial class ScoreEggs
	{
		public int collected_eggs;
		public int total_eggs;
		public ScoreEggs(int collected_eggs, int total_eggs)
		{
			this.collected_eggs = collected_eggs;
			this.total_eggs = total_eggs;
			BuildUI();
		}
	}
}