/* Generated by MyraPad at 09/05/2022 05:14:05 */
namespace Curse_of_the_Abyss
{
	public partial class ScoreTime
	{
		public int time;
		public ScoreTime(int time)
		{
			this.time = time;
			BuildUI();
		}
	}
}