/* Generated by MyraPad at 09/05/2022 05:14:05 */
namespace Curse_of_the_Abyss
{
	public partial class Score
	{
		public static int collected_eggs;
		public static int total_eggs;
		public Score()
		{
			BuildUI();
		}
	}
}