/* Generated by MyraPad at 08/05/2022 18:28:22 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Media;
using System;

namespace Curse_of_the_Abyss
{
	partial class Settings: Panel
	{
		public static int initial_height = 900;
		public static int initial_width = 1600;
		public static int curr_height = initial_height;
		public static int curr_width = initial_width;

		private void BuildUI(Game game)
		{
			double scale = MainMenu.scale;

			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>(MainMenu.path_to_bg);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/settings_logo.png");
			image2.Left = (int) Math.Round(640.0 * scale);
			image2.Top = (int) Math.Round(220 * scale);
			image2.Scale = new Vector2(0.5f * (float) scale, 0.5f * (float) scale);

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/UI/settings_bg.png");
			image3.Left = (int) Math.Round(525 * scale);
			image3.Top = (int) Math.Round(330 * scale);
			image3.Scale = new Vector2(0.7f * (float) scale, 0.7f * (float)scale);

			var textBox1 = new TextBox();
			textBox1.Text = "Resolution";
			textBox1.GridColumnSpan = 0;
			textBox1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox1.DisabledTextColor = Color.Black;
			textBox1.Left = (int) Math.Round(628 * scale);
			textBox1.Top = (int) Math.Round(444 * scale);
			textBox1.Enabled = false;
			textBox1.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox1.DisabledBackground = new SolidBrush("#00000000");

			var listItem0 = new ListItem();
			listItem0.Text = "Select ...";

			//disable suport for 4k res
			//var listItem1 = new ListItem();
			//listItem1.Text = "3840x2160";

			var listItem1 = new ListItem();
			listItem1.Text = "2560x1440";

			var listItem2 = new ListItem();
			listItem2.Text = "1920x1080";

			var listItem3 = new ListItem();
			listItem3.Text = "1600x900";

			var listItem4 = new ListItem();
			listItem4.Text = "1366x768";

			var listItem5 = new ListItem();
			listItem5.Text = "1280x720";


			var comboBox1 = new ComboBox();
			comboBox1.GridColumnSpan = 0;
			comboBox1.Left = (int)(810 * scale);
			comboBox1.Top = (int)(450 * scale);
			comboBox1.Width = (int)(125 * scale);
			comboBox1.Items.Add(listItem0);
			comboBox1.Items.Add(listItem1);
			comboBox1.Items.Add(listItem2);
			comboBox1.Items.Add(listItem3);
			comboBox1.Items.Add(listItem4);
			comboBox1.Items.Add(listItem5);
			comboBox1.SelectedItem = listItem0;

			var textButton1 = new TextButton();
			textButton1.Text = "Back";
			textButton1.GridColumnSpan = 0;
			textButton1.TextColor = Color.Black;
			textButton1.OverTextColor = Color.White;
			textButton1.PressedTextColor = Color.White;
			textButton1.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton1.PressedBackground = new SolidBrush("#00000000");
			textButton1.Left = (int)Math.Round(745 * scale);
			textButton1.Top = (int)Math.Round(730 * scale);
			textButton1.GridColumnSpan = 0;
			textButton1.Scale = new Vector2(0.45f * (float) scale, 0.45f * (float) scale);
			textButton1.Background = new SolidBrush("#00000000");
			textButton1.OverBackground = new SolidBrush("#00000000");
			textButton1.DisabledBackground = new SolidBrush("#00000000");
			textButton1.FocusedBackground = new SolidBrush("#00000000");
			textButton1.DisabledBorder = new SolidBrush("#00000000");

			var textButton2 = new TextButton();
            if (ResolutionSettings.IsFullscreen)
            {
				textButton2.Text = "Windowed";
			}
            else
            {
				textButton2.Text = "Fullscreen";
			}
			textButton2.TextColor = Color.Black;
			textButton2.OverTextColor = ColorStorage.CreateColor(235, 235, 235, 0);
			textButton2.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textButton2.PressedBackground = new SolidBrush("#00000000");
			textButton2.Left = (int)Math.Round(630 * scale);
			textButton2.Top = (int)Math.Round(480 * scale);
			textButton2.GridColumnSpan = 0;
			textButton2.GridRowSpan = 0;
			textButton2.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textButton2.Background = new SolidBrush("#00000000");
			textButton2.OverBackground = new SolidBrush("#00000000");
			textButton2.DisabledBackground = new SolidBrush("#00000000");
			textButton2.FocusedBackground = new SolidBrush("#00000000");

			var textBox3 = new TextBox();
			textBox3.Text = "Music volume";
			textBox3.TextColor = Color.Black;
			textBox3.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox3.Enabled = false;
			textBox3.DisabledTextColor = Color.Black;
			textBox3.Left = (int)Math.Round(630 * scale);
			textBox3.Top = (int)Math.Round(515 * scale);
			textBox3.GridColumnSpan = 0;
			textBox3.GridRowSpan = 0;
			textBox3.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox3.Background = new SolidBrush("#00000000");
			textBox3.OverBackground = new SolidBrush("#00000000");
			textBox3.DisabledBackground = new SolidBrush("#00000000");
			textBox3.FocusedBackground = new SolidBrush("#00000000");

			var textBox4 = new TextBox();
			textBox4.Text = "B";
			textBox4.TextColor = Color.Black;
			textBox4.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox4.Enabled = false;
			textBox4.DisabledTextColor = Color.Black;
			textBox4.Left = (int)Math.Round(630 * scale);
			textBox4.Top = (int)Math.Round(585 * scale);
			textBox4.GridColumnSpan = 0;
			textBox4.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox4.Background = new SolidBrush("#00000000");
			textBox4.OverBackground = new SolidBrush("#00000000");
			textBox4.DisabledBackground = new SolidBrush("#00000000");
			textBox4.FocusedBackground = new SolidBrush("#00000000");

			var textBox5 = new TextBox();
			textBox5.Text = "rightness";
			textBox5.TextColor = Color.Black;
			textBox5.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox5.Enabled = false;
			textBox5.DisabledTextColor = Color.Black;
			textBox5.Left = (int)Math.Round(643 * scale);
			textBox5.Top = (int)Math.Round(585 * scale);
			textBox5.GridColumnSpan = 0;
			textBox5.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox5.Background = new SolidBrush("#00000000");
			textBox5.OverBackground = new SolidBrush("#00000000");
			textBox5.DisabledBackground = new SolidBrush("#00000000");
			textBox5.FocusedBackground = new SolidBrush("#00000000");

			var textBox6 = new TextBox();
			textBox6.Text = "SFX volume";
			textBox6.TextColor = Color.Black;
			textBox6.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox6.Enabled = false;
			textBox6.DisabledTextColor = Color.Black;
			textBox6.Left = (int)Math.Round(630 * scale);
			textBox6.Top = (int)Math.Round(550 * scale);
			textBox6.GridColumnSpan = 0;
			textBox6.GridRowSpan = 0;
			textBox6.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox6.Background = new SolidBrush("#00000000");
			textBox6.OverBackground = new SolidBrush("#00000000");
			textBox6.DisabledBackground = new SolidBrush("#00000000");
			textBox6.FocusedBackground = new SolidBrush("#00000000");

			var textBox7 = new TextBox();
			textBox7.Text = "D";
			textBox7.TextColor = Color.Black;
			textBox7.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox7.Enabled = false;
			textBox7.DisabledTextColor = Color.Black;
			textBox7.Left = (int)Math.Round(630 * scale);
			textBox7.Top = (int)Math.Round(620 * scale);
			textBox7.GridColumnSpan = 0;
			textBox7.GridRowSpan = 0;
			textBox7.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox7.Background = new SolidBrush("#00000000");
			textBox7.OverBackground = new SolidBrush("#00000000");
			textBox7.DisabledBackground = new SolidBrush("#00000000");
			textBox7.FocusedBackground = new SolidBrush("#00000000");

			var textBox8 = new TextBox();
			textBox8.Text = "ifficulty";
			textBox8.TextColor = Color.Black;
			textBox8.Font = MyraEnvironment.DefaultAssetManager.Load<FontStashSharp.SpriteFontBase>("Content/UI/pieces_of_eight_108.fnt");
			textBox8.Enabled = false;
			textBox8.DisabledTextColor = Color.Black;
			textBox8.Left = (int)Math.Round(643 * scale);
			textBox8.Top = (int)Math.Round(620 * scale);
			textBox8.GridColumnSpan = 0;
			textBox8.GridRowSpan = 0;
			textBox8.Scale = new Vector2(0.28f * (float)scale, 0.28f * (float)scale);
			textBox8.Background = new SolidBrush("#00000000");
			textBox8.OverBackground = new SolidBrush("#00000000");
			textBox8.DisabledBackground = new SolidBrush("#00000000");
			textBox7.FocusedBackground = new SolidBrush("#00000000");

			var listItem6 = new ListItem();
			listItem6.Text = "Easy";

			var listItem7 = new ListItem();
			listItem7.Text = "Medium";

			var listItem8 = new ListItem();
			listItem8.Text = "Hard";


			var comboBox2 = new ComboBox();
			comboBox2.GridColumnSpan = 0;
			comboBox2.Left = (int)(810 * scale);
			comboBox2.Top = (int)(623 * scale);
			comboBox2.Width = (int)(125 * scale);
			comboBox2.Items.Add(listItem6);
			comboBox2.Items.Add(listItem7);
			comboBox2.Items.Add(listItem8);

			switch (Game.CurrDifficulty)
			{
				case Game.Diffculty.Easy:
					comboBox2.SelectedItem = listItem6;
					break;
				case Game.Diffculty.Medium:
					comboBox2.SelectedItem = listItem7;
					break;
				case Game.Diffculty.Hard:
					comboBox2.SelectedItem = listItem8;
					break;
				default:
					comboBox2.SelectedItem = listItem7;
					break;
			}
			
			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.Left = (int)Math.Round(810 * scale);
			horizontalSlider1.Top = (int)Math.Round(520 * scale);
			horizontalSlider1.Width = (int)Math.Round(125 * scale);
			horizontalSlider1.Value = 4 * MediaPlayer.Volume * 100;

			var horizontalSlider2 = new HorizontalSlider();
			horizontalSlider2.Left = (int)Math.Round(810 * scale);
			horizontalSlider2.Top = (int)Math.Round(590 * scale);
			horizontalSlider2.Width = (int)Math.Round(125 * scale);
			horizontalSlider2.Value = Brightness.brightnessValue;

			var horizontalSlider3 = new HorizontalSlider();
			horizontalSlider3.Left = (int)Math.Round(810 * scale);
			horizontalSlider3.Top = (int)Math.Round(555 * scale);
			horizontalSlider3.Width = (int)Math.Round(125 * scale);
			horizontalSlider3.Value = 2 * Game.sfx_vol * 100;

			Background = new SolidBrush("#00000000");
			DisabledBackground = new SolidBrush("#00000000");
			Widgets.Add(image1);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(textBox1);
			Widgets.Add(comboBox1);
			Widgets.Add(textButton1);
			Widgets.Add(textButton2);
			Widgets.Add(textBox3);
			Widgets.Add(horizontalSlider1);
			Widgets.Add(textBox4);
			Widgets.Add(textBox5);
			Widgets.Add(horizontalSlider2);
			Widgets.Add(textBox6);
			Widgets.Add(horizontalSlider3);
			Widgets.Add(textBox7);
			Widgets.Add(textBox8);
			Widgets.Add(comboBox2);


			// functionality

			textButton1.Click += (s, a) =>
			{
				Game._desktop.Root = Game._mainmenu;
			};

			textButton2.Click += (s, a) =>
			{
				ResolutionSettings.ToggleFullscreen();
				Game._mainmenu = new MainMenu(game);
				Game.res_changed = true;
			};

			horizontalSlider1.ValueChanged += (s, a) =>
			{
				MediaPlayer.Volume = 0.25f * (horizontalSlider1.Value / 100);
			};

			horizontalSlider2.ValueChanged += (s, a) =>
			{
				Brightness.brightnessValue = (byte) (horizontalSlider2.Value + 10f);
			};

			horizontalSlider3.ValueChanged += (s, a) =>
			{
				Game.sfx_vol = 0.5f * horizontalSlider3.Value / 100;
			};

			comboBox1.SelectedIndexChanged += (s, a) =>
			{
				int target_width;
				int target_height;
				switch (comboBox1.SelectedIndex)
				{
					case 1:
						target_width = 2560;
						target_height = 1440;
						MainMenu.path_to_bg = "Content/UI/MenuBackground_2k.png";
						Game.res_changed = true;
						break;
					case 2:
						target_width = 1920;
						target_height = 1080;
						Game.res_changed = true;
						break;
					case 3:
						target_width = 1600;
						target_height = 900;
						Game.res_changed = true;
						break;
					case 4:
						target_width = 1366;
						target_height = 768;
						Game.res_changed = true;
						break;
					case 5:
						target_width = 1280;
						target_height = 720;
						Game.res_changed = true;
						break;
					default:
						target_width = curr_width;
						target_height = curr_height;
						break;
				}

				MainMenu.scale = ((float)target_width / initial_width);
				ResolutionSettings.ChangeResolution(target_width, target_height);
				Game._mainmenu = new MainMenu(game);

				curr_width = target_width;
				curr_height = target_height;
			};


			comboBox2.SelectedIndexChanged += (s, a) =>
			{
				switch (comboBox2.SelectedIndex)
				{
					case 0:
						Game.CurrDifficulty = Game.Diffculty.Easy;
						break;
					case 1:
						Game.CurrDifficulty = Game.Diffculty.Medium;
						break;
					case 2:
						Game.CurrDifficulty = Game.Diffculty.Hard;
						break;
					default:
						Game.CurrDifficulty = Game.Diffculty.Medium;
						break;
				}
				Constants.init_constants();
			};
		}

		
	}
}
